name: 绝区零接待回复

on:
  schedule:
    - cron: '0 2 * * *'
    - cron: '0 4 * * *'
    - cron: '0 6 * * *'
    - cron: '0 8 * * *'
    - cron: '0 10 * * *'
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  run-python-files:
    runs-on: ubuntu-latest

    steps:
    - name: 检查仓库
      uses: actions/checkout@v3

    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: 安装所需库
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: HLX-内向的猫-接待回复签到
      run: python zzz/zzzre.py | tee output.log
      env:
        PYTHONUNBUFFERED: 1